import React, { useState } from 'react';
import Button from './ui/Button';
import InputField from './ui/InputField';
import TextAreaField from './ui/TextAreaField';
import Card from './ui/Card';
import { PhoneIcon, EnvelopeIcon, MapPinIcon, ChatBubbleLeftEllipsisIcon, CheckCircleIcon, XCircleIcon } from './icons/HeroIcons';

interface ContactSectionProps {
  googleScriptUrl: string;
}

const ContactSection: React.FC<ContactSectionProps> = ({ googleScriptUrl }) => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [subject, setSubject] = useState('');
  const [message, setMessage] = useState('');
  
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isLoading, setIsLoading] = useState(false);
  const [submissionStatus, setSubmissionStatus] = useState<'success' | 'error' | null>(null);
  const [submissionMessage, setSubmissionMessage] = useState('');

  const emailRegex = new RegExp("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$");

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    if (!name.trim()) newErrors.name = 'নাম আবশ্যক।';
    if (!email.trim()) {
      newErrors.email = 'ইমেইল আবশ্যক।';
    } else if (!emailRegex.test(email.trim())) {
      newErrors.email = 'সঠিক ইমেইল ঠিকানা দিন।';
    }
    if (!subject.trim()) newErrors.subject = 'বিষয় আবশ্যক।';
    if (!message.trim()) newErrors.message = 'বার্তা আবশ্যক।';
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const resetForm = () => {
    setName('');
    setEmail('');
    setSubject('');
    setMessage('');
    setErrors({});
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmissionStatus(null);
    setSubmissionMessage('');

    if (!validate()) return;

    if (googleScriptUrl === "YOUR_GOOGLE_APPS_SCRIPT_URL_FOR_CONTACT_FORM") {
      setSubmissionStatus('error');
      setSubmissionMessage('❌ গুগল অ্যাপস স্ক্রিপ্ট URL সেট করা হয়নি। অনুগ্রহ করে অ্যাডমিনের সাথে যোগাযোগ করুন।');
      setIsLoading(false);
      return;
    }

    setIsLoading(true);

    const payloadForGAS = {
      // action: "addContactMessage", // The provided script does not use an action property
      name: name.trim(),
      email: email.trim(),
      subject: subject.trim(),
      message: message.trim(),
      // Timestamp is generated by the Google Apps Script, so not needed here.
    };

    try {
      const response = await fetch(googleScriptUrl, {
        method: 'POST',
        mode: 'cors',
        cache: 'no-cache',
        headers: {
          'Content-Type': 'text/plain', 
        },
        redirect: 'follow',
        body: JSON.stringify(payloadForGAS),
      });

      let responseData;
      const textResponse = await response.text();
      try {
        responseData = JSON.parse(textResponse);
      } catch (e) {
         console.warn("Could not parse JSON response from contact form submission", textResponse, e);
         // If response is OK and text indicates success (though script returns JSON)
         if (response.ok && textResponse.toLowerCase().includes("success")) { 
            responseData = { result: "success", message: "সফলভাবে জমা হয়েছে (তবে সার্ভার থেকে বিস্তারিত তথ্য আসেনি)।" };
         } else if (response.ok) { // OK response but not the expected JSON
            responseData = { result: "error", message: `সার্ভার থেকে একটি অপ্রত্যাশিত উত্তর এসেছে: ${textResponse.substring(0,100)}`};
         } else { // Not OK response
            responseData = { result: "error", message: textResponse || "একটি অজানা ত্রুটি ঘটেছে।" };
         }
      }
      
      if (response.ok && responseData && responseData.result === 'success') {
        setSubmissionStatus('success');
        // The script returns { result: "success" }, so there's no custom message from server.
        setSubmissionMessage('✅ আপনার বার্তা সফলভাবে পাঠানো হয়েছে। আমরা শীঘ্রই আপনার সাথে যোগাযোগ করবো।');
        resetForm();
      } else {
         // Use message from responseData if available, otherwise a generic error
         const errorMessage = responseData?.message || responseData?.error || `বার্তা পাঠানো যায়নি (সার্ভার থেকে ত্রুটিপূর্ণ উত্তর: ${response.status})।`;
         throw new Error(errorMessage);
      }
    } catch (error) {
      console.error('Contact form submission error:', error);
      setSubmissionStatus('error');
      setSubmissionMessage(error instanceof Error ? `❌ ${error.message}` : '❌ বার্তা পাঠানো যায়নি। নেটওয়ার্ক বা সার্ভার সমস্যা হতে পারে।');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-8">
      <Card className="p-6 md:p-8">
        <h2 className="text-3xl font-bold text-red-700 mb-8 text-center flex items-center justify-center">
          <PhoneIcon className="w-8 h-8 mr-3 text-red-600" />
          যোগাযোগ ও সহায়তা
        </h2>
        
        <div className="grid md:grid-cols-2 gap-8">
          {/* Contact Information */}
          <div className="space-y-6">
            <h3 className="text-xl font-semibold text-gray-800">আমাদের সাথে যোগাযোগ করুন</h3>
            <div className="space-y-3 text-gray-700">
              <p className="flex items-start">
                <MapPinIcon className="w-6 h-6 mr-3 text-red-500 flex-shrink-0 mt-1" />
                <span>প্রধান কার্যালয়: খানসামা বাজার, খানসামা, দিনাজপুর।</span>
              </p>
              <p className="flex items-center">
                <PhoneIcon className="w-5 h-5 mr-3 text-red-500" />
                হেল্পলাইন: <a href="tel:+8801XXXXXXXXX" className="text-red-600 hover:underline ml-1">+৮৮০১xxxxxxxxx</a>
              </p>
              <p className="flex items-center">
                <EnvelopeIcon className="w-5 h-5 mr-3 text-red-500" />
                ইমেইল: <a href="mailto:info@khansamablood.org" className="text-red-600 hover:underline ml-1">info@khansamablood.org</a>
              </p>
            </div>
            <div className="mt-6">
              <h4 className="text-md font-semibold text-gray-800 mb-2">সোশ্যাল মিডিয়াতে আমরা</h4>
              <div className="flex space-x-4">
                <a href="#" target="_blank" rel="noopener noreferrer" className="text-red-600 hover:text-red-800 transition-colors">ফেসবুক</a>
                <a href="#" target="_blank" rel="noopener noreferrer" className="text-red-600 hover:text-red-800 transition-colors">টুইটার</a>
                <a href="#" target="_blank" rel="noopener noreferrer" className="text-red-600 hover:text-red-800 transition-colors">ইনস্টাগ্রাম</a>
              </div>
            </div>
          </div>

          {/* Contact Form */}
          <div>
            <h3 className="text-xl font-semibold text-gray-800 mb-4">আপনার বার্তা পাঠান</h3>
            <form onSubmit={handleSubmit} className="space-y-5">
              <InputField id="contactName" label="আপনার নাম" value={name} onChange={e => setName(e.target.value)} error={errors.name} required placeholder="আপনার সম্পূর্ণ নাম" disabled={isLoading} />
              <InputField id="contactEmail" label="আপনার ইমেইল" type="email" value={email} onChange={e => setEmail(e.target.value)} error={errors.email} required placeholder="your.email@example.com" disabled={isLoading} />
              <InputField id="contactSubject" label="বিষয়" value={subject} onChange={e => setSubject(e.target.value)} error={errors.subject} required placeholder="আপনার বার্তার বিষয়" disabled={isLoading} />
              <TextAreaField id="contactMessage" label="আপনার বার্তা" value={message} onChange={e => setMessage(e.target.value)} error={errors.message} required placeholder="বিস্তারিত লিখুন..." disabled={isLoading} />
              
              {submissionStatus && (
                <div className={`p-3 rounded-md text-center flex items-center justify-center ${submissionStatus === 'success' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                  {submissionStatus === 'success' ? <CheckCircleIcon className="w-5 h-5 mr-2" /> : <XCircleIcon className="w-5 h-5 mr-2" />}
                  {submissionMessage}
                </div>
              )}

              <Button type="submit" variant="primary" className="w-full" leftIcon={<ChatBubbleLeftEllipsisIcon className="w-5 h-5"/>} isLoading={isLoading} disabled={isLoading}>
                {isLoading ? 'পাঠানো হচ্ছে...' : 'বার্তা পাঠান'}
              </Button>
            </form>
          </div>
        </div>
      </Card>
    </div>
  );
};

export default ContactSection;